#!/bin/sh
# --------- Gradle Wrapper script ---------
# This is a placeholder. The real gradlew is a binary script generated by Gradle.
echo "Gradle wrapper missing. Please generate it with './gradlew wrapper' from a local Gradle install or add the wrapper files to your repo."
exit 1
